### ISSUE TITLE
add new member

### ISSUE THREAD

**Issue by k-okada** [ros-drivers-gbp/axis_camera-release#1]
@dirk-thomas can you give me a permission to add new people for this repository? 
https://github.com/orgs/ros-drivers-gbp/teams/camera_drivers

**Comment by dirk-thomas** [comment]
Done.

**Comment by k-okada** [comment]
Thank you, but I can not add new user to this reposotory. May be I need admin permission?
Anyway I just want to give @tonybaltovski a write permission, so that he can run bloom-release

**Comment by tonybaltovski** [comment]
@k-okada, I wouldn't mind helping maintain this driver as many Clearpath robots do use it.

**Comment by dirk-thomas** [comment]
@k-okada As a maintainer of the `camera_drivers` team you should be able to add (and remove) members to that team. Can you please try that.

**Comment by jack-oquin** [comment]
@k-okada, @dirk-thomas: for some reason, the **camera_drivers** team (of which Kei is a member) has only write access and not admin. I see no reason not to upgrade that access.

**Comment by dirk-thomas** [comment]
@jack-oquin The access to the repos within the team should be orthogonal to the role he has which is necessary to add/remove member to the same team.

Please feel free to also change the access level if you think that would be helpful for other stuff.

**Comment by jack-oquin** [comment]
@dirk-thomas: I don't understand very clearly what can and cannot be done with various github access authority levels. In my experience as a maintainer, there have been times I needed admin authority to do certain things, but I don't recall exactly what they were.

Since this is a GBP repository, maintainers make up its developer base. I don't see anyone inexperienced in the **camera_drivers** team, so I'll go ahead and upgrade it.

**Comment by k-okada** [comment]
@dirk-thomas @jack-oquin thank you for support , @tonybaltovski added as a member of `camera_drivers` and i think it's ready to release axis_camera to indigo.

**Comment by tonybaltovski** [comment]
Thanks @k-okada, I bloomed a release last night.

**Comment by k-okada** [comment]
thanks, btw can I ask why your company interested in this camera so much? I
thought is camera is for surveillance and actually we put this camera on
ceiling and record the research experiments, never thought of putting on
the mobile robot...

--
◉ Kei Okada


2018-02-16 9:47 GMT+09:00 Tony Baltovski <notifications@github.com>:
